### ISSUE TITLE
German Wording

### ISSUE THREAD

**Issue by ArneBo** [S3-working-group/s3-illustrations#1]
Danke Bernhard, für die gute Arbeit! Welch ein Geschenk!
Ich habe mich total gefreut über einige Formulierungen bei denen ich noch viele Anglizismen verwende: "_Entwicklungsgespräch_" gefällt mir am Besten!

Ein paar Dinge könnte man aber glaube ich noch verbessern, sorry das ich nur ein Issue daraus mache:
- Ich würde vorschlagen **Proposal Forming Vorschlagsbildung** zu nennen.
Kommt so glaube ich nur in der Patternkollektion vor.
https://github.com/S3-working-group/s3-illustrations/blob/master/de/png/140dpi-transparent/general/s3-patterns-map.png
Ich bin mir nicht 100%ig sicher ob _picture forming_ das gleiche ist wie _proposal forming_, aber ich glaube schon. Im Beschlusstemplate steht "_Bildformung_"
https://github.com/S3-working-group/s3-illustrations/blob/master/de/png/140dpi-transparent/agreements/agreement-template.png

- Verantwortlichkeit würde ich Verantwortung nennen.
https://github.com/S3-working-group/s3-illustrations/blob/master/de/png/140dpi-transparent/general/s3-principles-plain.png

- Das Pull-prinzip beschreibe ich gerne mit bedarfs- oder bedürfnissorientiertem Handeln. Ganz nach dem Treiber. Vielleicht bringt das ja noch ein bisschen Mehrwert diese Querverbindung mit Agile.
Leider finde ich nicht mehr wo das steht..

Wäre vielleicht spannend sich mal die Holländischen Originalwörter anzuschauen, vielleicht lässt sich daraus noch ein Quäntchen Mehrwert extrahieren.

**Comment by ArneBo** [comment]
_Gastgeber_ ist auch viel schöner als _Sekretär_, darüber hab ich mich auch gefreut!
Blöd finde ich ja die Genderdebatte im Deutschen bei Rollen.. Damit wird man allerdings nur in alternativen Kreisen konfrontiert :) Ich bemühe mich aus eigener Motivation immer neutrale Bezeichnungen zu finden oder umgekehrt zu gendern wie Sekretär oder Protokollantin. 
Ich würde S3 auch eher als matriarchisch bezeichnen, vielleicht wollen wir aus Prinzip gleich alle Rollen feminisieren :)

**Comment by bboc** [comment]
Bin gerade nochmal auf das Ticket gestossen, weil ich die gerade die neuen Pattern-Namen übersetze, hier also ein paar Anmerkungen.

* In einem Pull-System entscheiden diejenigen, die die Arbeit tun, selbst, wann sie bereit sind, mit einer neue Arbeitsaufgabe zu beginnen. Das betrifft dann auch die Auswahl der Aufgaben innerhalb eines Teams, jedes Teammitglied zieht sich die Aufgabe, die für ihn/sie im Moment am geeignetsten (Balance aus Kapazität, Skill, Wichtigkeit) scheint. Das Gegenteil ist ein Push-System, bei dem ein Manager den Mitarbeitern Aufgaben zuordnet, und i.d.R. auch Fertigstellungstermine zuteilt. Insofern trifft "bedarfs- oder bedürfnisorientiertem Handeln" nicht ganz den Kern der Sache.
* "Verantwortung" ist eine gute Idee
* Picture-Forming ist der "nicht-kreative" Teil des Proposal-Forming, in dem man sich einen Überblick verschafft, worum es eigentlich geht (also Treiber verstehen, Dimension des Themas erfassen, Fragen suchen und, soweit möglich, auch beantworten). Die Ideensammlung und das Erarbeiten des tatsächlichen Vorschlags (Tuning) sind dann der "kreative" Teil
* "Vorschlagsbildung" ist eine treffende Übersetzung, und hat daher, genauso wie das Original "Proposal Forming" im Englischen, einen Nachteil: es klingt so, als sei ginge es um Vorschlagsbildung im Allgemeinen, und auch wenn es Menschen gibt, die denken, das sei der einzige Weg, in einer Gruppe Vorschläge zu erarbeiten, ist das natürlich nicht so. Der Englische Begriff macht es meiner Ansicht nach leichter, klarzustellen, dass es sich hierbei nur um ein mögliches Verfahren von vielen handelt. 

Die Genderdebatte ist Teil unserer Kultur, unsere Sprache bietet nunmal die Unterscheidung zwischen männlichen und weiblichen Formen, die es im Englischen so nicht gibt. Darauf müssen wir bei der Vermittlung von S3 im deutschsprachigen Raum reagieren, und eine Form finden, die sowohl für die Zielgruppe als auch für die Trainer funktioniert. Zum Glück haben wir ja gute Werkzeuge, um schwierige Entscheidungen zu treffen und zu entwickeln ;-)
